export default {
  pages: ["home", "search", "add recipe", "contact"],
  foodSubjects: [
    "favorites",
    "breakfast",
    "dinner",
    "dessert",
    "bread",
    "sauce/dip",
    "drink",
    "soup",
    "salad",
    "cookies",
    "cake",
    "pie",
    "other"
  ],
  CLOUDINARY_UPLOAD_PRESET: "um4mdnly",
  CLOUDINARY_UPLOAD_URL: "https://api.cloudinary.com/v1_1/gdevany/upload",
  cloudinaryPojectFile: "recipes/recipes/",
  projectMainImageTag: "recipehead",
  loggedIn: false,
  projectChosen: "",
  searchTagChosen: "",
  pageSelected: "home",
  logo: "ydsyummys.png",
  cloudName: "gdevany",
  cloudinaryFilePath: "recipes/recipes",
  landingPic: "poolImage3.jpg"
};
