export default {
  pages: ["home", "search", "add recipe", "contact"],
  subjects: [
    "Favorite recipe",
    "Breakfast recipe",
    "Dinner recipe",
    "Dessert recipe",
    "Bread recipe",
    "Sauce/Dip recipe",
    "Drink recipe",
    "Soup recipe",
    "Salad recipe",
    "Cookies recipe",
    "Cake recipe",
    "Pie recipe",
    "Other recipe"
  ],
  CLOUDINARY_UPLOAD_PRESET: "um4mdnly",
  CLOUDINARY_UPLOAD_URL: "https://api.cloudinary.com/v1_1/gdevany/upload",
  cloudinaryPojectFile: "recipes/recipes/",
  projectMainImageTag: "recipehead",
  appSubject: "recipeReact",
  loggedIn: false,
  projectChosen: "",
  searchTagChosen: "recipehead",
  pageSelected: "home",
  // logo: "recipesReactLogo2.png",
  logo: "logoSteelImage.png",
  cloudName: "gdevany",
  cloudinaryFilePath: "recipes/recipes",
  landingPic: "steelImage.jpg"
};
