export default {
  theme: "theme-dark",
  pages: ["home", "search", "add recipe", "contact"],
  subjects: [
    "favorite recipe",
    "breakfast recipe",
    "dinner recipe",
    "dessert recipe",
    "bread recipe",
    "sauce/Dip recipe",
    "drink recipe",
    "soup recipe",
    "salad recipe",
    "cookies recipe",
    "cake recipe",
    "pie recipe",
    "other recipe"
  ],
  CLOUDINARY_UPLOAD_PRESET: "um4mdnly",
  CLOUDINARY_UPLOAD_URL: "https://api.cloudinary.com/v1_1/gdevany/upload",
  cloudinaryPojectFile: "recipes/recipes/",
  projectMainImageTag: "recipehead",
  appSubject: "recipeReact",
  loggedIn: false,
  projectChosen: "",
  searchTagChosen: "recipehead",
  pageSelected: "home",
  // logo: "recipesReactLogo2.png",
  logo: "logoSteelImage.png",
  cloudName: "gdevany",
  cloudinaryFilePath: "recipes/recipes",
  landingPic: "steelImage.jpg"
};
